# (Opcional) redirección HTTP -> HTTPS
server {
  listen 80;
  server_name _;
  return 301 https://$host$request_uri;
}

# Sitio (HTTPS). Si aún no tienes certs, cambia a: listen 80; y comenta ssl_*.
server {
  listen  80;
  server_name _;

  # Seguridad básica
  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options DENY always;
  add_header X-XSS-Protection "1; mode=block" always;
  add_header Referrer-Policy no-referrer-when-downgrade always;
  add_header Permissions-Policy "geolocation=(), microphone=()" always;

  # Angular estático
  root /usr/share/nginx/html;
  index index.html;

  # Angular SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # API → NestJS interno
  location /api/ {
    proxy_pass http://api_srv:3000/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";
  }

  client_max_body_size 20m;
}
